"""Download packaging helpers for HTML/ZIP/source exports."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Iterable, Optional, Tuple
from zipfile import ZipFile, ZIP_DEFLATED
import re

from app.models.db.page import Page
from app.models.db.snapshot import Snapshot
from app.services.template_renderer import (
    build_inline_styles,
    get_runtime_script_tag,
    strip_script_tags,
)
from app.services.validator import extract_body_content


@dataclass
class DownloadOptions:
    format: str
    include_runtime: bool = True
    include_comments: bool = False
    include_metadata: bool = False


def _slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"^-+|-+$", "", value)
    return value or "zaoya-project"


def _metadata_block(snapshot: Snapshot) -> str:
    return (
        f'<meta name="zaoya:project" content="{snapshot.project_id}">\n'
        f'<meta name="zaoya:snapshot" content="{snapshot.id}">\n'
        f'<meta name="zaoya:generated" content="{datetime.utcnow().isoformat()}">'
    )


def generate_html(
    snapshot: Snapshot,
    page: Page,
    options: DownloadOptions,
    lang: str = "en",
    title: Optional[str] = None,
) -> str:
    """Generate standalone HTML file for a single page."""
    title = title or page.title or "Zaoya Page"
    metadata = _metadata_block(snapshot) if options.include_metadata else ""
    comments = (
        f"Generated by Zaoya on {datetime.utcnow().isoformat()}."
        if options.include_comments
        else "Zaoya generated HTML"
    )
    runtime_script = get_runtime_script_tag() if options.include_runtime else ""
    body_html = strip_script_tags(extract_body_content(page.html or ""))
    styles = build_inline_styles(body_html)

    return f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  {metadata}
  {styles}
  <style>/* {comments} */</style>
</head>
<body class="bg-white min-h-screen">
  {body_html}
  {runtime_script}
</body>
</html>
"""


def build_zip_package(
    snapshot: Snapshot,
    pages: Iterable[Page],
    options: DownloadOptions,
    include_source: bool = False,
) -> Tuple[bytes, str]:
    """Build a ZIP package for the given pages."""
    project_slug = _slugify(getattr(snapshot, "summary", "") or "zaoya-project")
    zip_buffer = BytesIO()

    with ZipFile(zip_buffer, "w", compression=ZIP_DEFLATED) as zf:
        for page in pages:
            filename = "index.html" if page.is_home else f"{page.slug}.html"
            html = generate_html(snapshot, page, options)
            zf.writestr(filename, html)

        if include_source:
            zf.writestr(
                "styles.css",
                "/* Tailwind CSS has been inlined in the HTML. */\n",
            )

        if options.include_runtime:
            runtime_content = _load_runtime_script()
            if runtime_content:
                zf.writestr("zaoya-runtime.js", runtime_content)

    zip_buffer.seek(0)
    return zip_buffer.read(), f"{project_slug}.zip"


def _load_runtime_script() -> Optional[str]:
    """Attempt to load the runtime script from local assets, fallback to stub."""
    candidates = [
        Path(__file__).resolve().parents[3] / "frontend" / "public" / "zaoya-runtime.js",
        Path(__file__).resolve().parents[3] / "frontend" / "dist" / "zaoya-runtime.js",
    ]
    for path in candidates:
        if path.exists():
            return path.read_text(encoding="utf-8")
    return "// Zaoya runtime unavailable. Use the hosted runtime instead.\n"
